Update source to openquake inputs
OpenDRR/opendrr-api pull request #123
Opened 2021-06-21 21:03 UTC by drotheram

Migrate input data from `model-inputs` repo to `openquake-inputs` repo.

- Changes to source repos
- Changes to filenames
- Removal of retrofit costs

Changes defined by requirements outlined in:
https://github.com/OpenDRR/opendrr-api/issues/104

Closes #104

2021-06-22 13:14 UTC, anthonyfok approved these changes
Looks good to me!  Thank you Drew (and Will) for your great work!

2021-06-24 21:33 UTC, wkhchow commented on python/add_data.sh
> +    exposure/general-building-stock/1. documentation/retrofit_costs.csv
should this be %20 to keep the same as above?

2021-06-24 22:34 UTC, wkhchow requested changes
few issues I noticed on the latest db dump
- [ ] mh.mh_rating_thresholds table is empty in the db.  Looks like csv is fetch in the stack, but not copied into the db  table in copyAncillaryTables.py.  Causes the result tables to be empty, and probably why the views are missing as well.
- [ ] vs30.vs30_can_site_model table is empty, I see in the copyAncillaryTables.py so not sure whats going on?  All the vs30_can_site_model_metrovan_*_exposure_xref tables are empty as well since vs30_can_site table is empty.

Besides that all looks good.

2021-06-24 23:11 UTC, drotheram commented
Will add the mh_ratings_thresholds loading line. 

Traced the vs30_can_site_model table and found this error while loading with a Python system call to psql:

```
copy vs30.vs30_can_site_model (lon, lat, vs30, z1pt0, z2pt5) FROM '/usr/src/app/site-vgrid_CA.csv' WITH DELIMITER AS ',' CSV HEADER ;
ERROR:  unquoted newline found in data
HINT:  Use quoted CSV field to represent newline.
CONTEXT:  COPY vs30_can_site_model, line 2222069
256
```

2021-06-25 00:08 UTC, drotheram commented
Fixed mh_rating_thresholds table copy command in model-factory

2021-06-28 16:26 UTC, wkhchow approved these changes

2021-06-28 17:12 UTC, wkhchow requested changes
awaiting db dump to verify again before approving.

2021-06-29 21:27 UTC, jvanulde approved these changes
Looks fine to me.

2021-06-29 21:56 UTC, wkhchow approved these changes

2021-06-29 21:56 UTC, merged